// Check Internet
export const CHECK_INTERNET = 'CHECK_INTERNET';

// Set Snack Alert
export const SET_SNACK_ALERT = 'SET_SNACK_ALERT';

// Set Fore Ground Push Notifications
export const SET_FORE_PUSH_NOTIFICATION = 'SET_FORE_PUSH_NOTIFICATION';

// Clear Fore Ground Push Notifications
export const CLEAR_FORE_PUSH_NOTIFICATION = 'CLEAR_FORE_PUSH_NOTIFICATION';

// Clear Snack Alert
export const CLEAR_SNACK_ALERT = 'CLEAR_SNACK_ALERT';

// Set Custom Theme
export const SET_CUSTOM_THEME = 'SET_CUSTOM_THEME';

// Set QR Code Data
export const SET_QR_CODE_DATA = 'SET_QR_CODE_DATA';

// Authenticate User
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

// Refresh token
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

// Post Login OTP
export const LOGIN_OTP = 'LOGIN_OTP';
export const LOGIN_OTP_SUCCESS = 'LOGIN_OTP_SUCCESS';
export const LOGIN_OTP_FAILURE = 'LOGIN_OTP_FAILURE';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';

// Register new User
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// Forgot Password
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

// Change Password
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// Ge Market Data
export const GET_MARKET_DATA = 'GET_MARKET_DATA';
export const GET_MARKET_DATA_SUCCESS = 'GET_MARKET_DATA_SUCCESS';
export const GET_MARKET_DATA_FAILURE = 'GET_MARKET_DATA_FAILURE';

// Ge Market Data of Coin
export const GET_MARKET_DATA_OF_COIN = 'GET_MARKET_DATA_OF_COIN';
export const GET_MARKET_DATA_OF_COIN_SUCCESS =
  'GET_MARKET_DATA_OF_COIN_SUCCESS';
export const GET_MARKET_DATA_OF_COIN_FAILURE =
  'GET_MARKET_DATA_OF_COIN_FAILURE';

// SET User Data
export const SET_USER_DATA = 'SET_USER_DATA';

// Clear Auth State
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

// Add Bank Details
export const ADD_BANK_DETAILS = 'ADD_BANK_DETAILS';
export const ADD_BANK_DETAILS_SUCCESS = 'ADD_BANK_DETAILS_SUCCESS';
export const ADD_BANK_DETAILS_FAILURE = 'ADD_BANK_DETAILS_FAILURE';

// Get Bank Details
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';
export const GET_BANK_DETAILS_SUCCESS = 'GET_BANK_DETAILS_SUCCESS';
export const GET_BANK_DETAILS_FAILURE = 'GET_BANK_DETAILS_FAILURE';

// Get Bank Details Wallet
export const GET_BANK_DETAILS_WALLET = 'GET_BANK_DETAILS_WALLET';
export const GET_BANK_DETAILS_WALLET_SUCCESS =
  'GET_BANK_DETAILS_WALLET_SUCCESS';
export const GET_BANK_DETAILS_WALLET_FAILURE =
  'GET_BANK_DETAILS_WALLET_FAILURE';

// Delete Bank Details
export const DELETE_BANK_DETAILS = 'DELETE_BANK_DETAILS';
export const DELETE_BANK_DETAILS_SUCCESS = 'DELETE_BANK_DETAILS_SUCCESS';
export const DELETE_BANK_DETAILS_FAILURE = 'DELETE_BANK_DETAILS_FAILURE';

//Add kyc Details
export const ADD_KYC_DETAILS = 'ADD_KYC_DETAILS';
export const ADD_KYC_DETAILS_SUCCESS = 'ADD_KYC_DETAILS_SUCCESS';
export const ADD_KYC_DETAILS_FAILURE = 'ADD_KYC_DETAILS_FAILURE';

//Get kyc Details
export const GET_KYC_DETAILS = 'GET_KYC_DETAILS';
export const GET_KYC_DETAILS_SUCCESS = 'GET_KYC_DETAILS_SUCCESS';
export const GET_KYC_DETAILS_FAILURE = 'GET_KYC_DETAILS_FAILURE';

//Get IFSC Code Bank Details
export const GET_IFSC_CODE_BANK_DETAILS = 'GET_IFSC_CODE_BANK_DETAILS';
export const GET_IFSC_CODE_BANK_DETAILS_SUCCESS =
  'GET_IFSC_CODE_BANK_DETAILS_SUCCESS';
export const GET_IFSC_CODE_BANK_DETAILS_FAILURE =
  'GET_IFSC_CODE_BANK_DETAILS_FAILURE';

// Clear IFSC Code bank Details
export const CLEAR_IFSC_CODE_BANK_DETAILS = 'CLEAR_IFSC_CODE_BANK_DETAILS';

// Logout
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// ADD Support User
export const SUPPORT_USER = 'SUPPORT_USER';
export const SUPPORT_USER_SUCCESS = 'SUPPORT_USER_SUCCESS';
export const SUPPORT_USER_FAILURE = 'SUPPORT_FAILURE';

// Get Support Details
export const GET_SUPPORT_DETAILS = 'GET_SUPPORT_DETAILS';
export const GET_SUPPORT_DETAILS_SUCCESS = 'GET_SUPPORT_DETAILS_SUCCESS';
export const GET_SUPPORT_DETAILS_FAILURE = 'GET_SUPPORT_DETAILS_FAILURE';

//Get Support View Details
export const SUPPORT_USER_GET_VIEW_DETAILS = 'SUPPORT_USER_GET_VIEW_DETAILS';
export const SUPPORT_USER_GET_VIEW_DETAILS_SUCCESS =
  'SUPPORT_USER_GET_VIEW_DETAILS_SUCCESS';
export const SUPPORT_USER_GET_VIEW_DETAILS_FAILURE =
  'SUPPORT_USER_GET_VIEW_DETAILS_FAILURE';

//Manual Deposit
export const GET_BANK_LIST = 'GET_BANk_LIST';
export const POST_MANUAL_DEPOSIT = 'POST_MANUAL_DEPOSIT';
export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';
export const GET_ACCOUNT_DETAILS_FAILURE = 'GET_ACCOUNT_DETAILS_FAILURE';
export const GET_BANK_DROP_DOWN = 'GET_BANK_DROP_DOWN';
export const GET_BANK_DROP_DOWN_SUCCESS = 'GET_BANK_DROP_DOWN_SUCCESS';
export const GET_BANK_DROP_DOWN_FAILURE = 'GET_BANK_DROP_DOWN_FAILURE';
export const POST_DEPOSIT_AMOUNT = 'POST_DEPOSIT_AMOUNT';
export const POST_DEPOSIT_AMOUNT_SUCCESSS = 'POST_DEPOSIT_AMOUNT_SUCCESSS';
export const POST_DEPOSIT_AMOUNT_FAILURE = 'POST_DEPOSIT_AMOUNT_FAILURE';
//Withdraw Amount
export const POST_WITHDRAW_OTP = 'POST_WITHDRAW_OTP';
export const POST_WITHDRAW_OTP_SUCCESS = 'POST_WITHDRAW_OTP_SUCCESS';
export const POST_WITHDRAW_OTP_FAILURE = 'POST_WITHDRAW_OTP_FAILURE';

export const POST_WITHDRAW_AMOUNT = 'POST_WITHDRAW_AMOUNT';
export const POST_WITHDRAW_AMOUNT_SUCCESS = 'POST_WITHDRAW_AMOUNT_SUCCESS';
export const POST_WITHDRAW_AMOUNT_FAILURE = 'POST_WITHDRAW_AMOUNT_FAILURE';

export const POST_WITHDRAW_AMOUNT_ALL_COINS = 'POST_WITHDRAW_AMOUNT_ALL_COINS';
export const POST_WITHDRAW_AMOUNT_ALL_COINS_SUCCESS =
  'POST_WITHDRAW_AMOUNT_ALL_COINS_SUCCESS';
export const POST_WITHDRAW_AMOUNT_ALL_COINS_FAILURE =
  'POST_WITHDRAW_AMOUNT_ALL_COINS_FAILURE';

// Clear Post Withdraw Amount
export const CLEAR_WITHDRAW_AMOUNT = 'CLEAR_WITHDRAW_AMOUNT';
export const CLEAR_WITHDRAW_AMOUNT_ALL_COINS =
  'CLEAR_WITHDRAW_AMOUNT_ALL_COINS';

export const GET_WITHDRAW_FEE = 'GET_WITHDRAW_FEE';
export const GET_WITHDRAW_FEE_SUCCESS = 'GET_WITHDRAW_FEE_SUCCESS';
export const GET_WITHDRAW_FEE_FAILURE = 'GET_WITHDRAW_FEE_FAILURE';
// Get Wallet Data
export const GET_WALLET_DATA = 'GET_WALLET_DATA';
export const GET_WALLET_DATA_SUCCESS = 'GET_WALLET_DATA_SUCCESS';
export const GET_WALLET_DATA_FAILURE = 'GET_WALLET_DATA_FAILURE';

// Get In Order Data
export const GET_INORDER_DATA = 'GET_INORDER_DATA';
export const GET_INORDER_DATA_SUCCESS = 'GET_INORDER_DATA_SUCCESS';
export const GET_INORDER_DATA_FAILURE = 'GET_INORDER_DATA_FAILURE';

// Get Deposit Transaction History
export const GET_DEPOSIT_TRANSACTION_HISTORY =
  'GET_DEPOSIT_TRANSACTION_HISTORY';
export const GET_DEPOSIT_TRANSACTION_HISTORY_SUCCESS =
  'GET_DEPOSIT_TRANSACTION_HISTORY_SUCCESS';
export const GET_DEPOSIT_TRANSACTION_HISTORY_FAILURE =
  'GET_DEPOSIT_TRANSACTION_HISTORY_FAILURE';

// Get Withdraw Transaction History
export const GET_WITHDRAW_TRANSACTION_HISTORY =
  'GET_WITHDRAW_TRANSACTION_HISTORY';
export const GET_WITHDRAW_TRANSACTION_HISTORY_SUCCESS =
  'GET_WITHDRAW_TRANSACTION_HISTORY_SUCCESS';
export const GET_WITHDRAW_TRANSACTION_HISTORY_FAILURE =
  'GET_WITHDRAW_TRANSACTION_HISTORY_FAILURE';

//Get Address for Coin
export const GET_ADDRESS_FOR_COIN = 'GET_ADDRESS_FOR_COIN';
export const GET_ADDRESS_FOR_COIN_SUCCESS = 'GET_ADDRESS_FOR_COIN_SUCCESS';
export const GET_ADDRESS_FOR_COIN_FAILURE = 'GET_ADDRESS_FOR_COIN_FAILURE';

//Get Exchange order data for Coin
export const GET_EXCHANGE_ORDER_DATA_FOR_COIN =
  'GET_EXCHANGE_ORDER_DATA_FOR_COIN';
export const GET_EXCHANGE_ORDER_DATA_FOR_COIN_SUCCESS =
  'GET_EXCHANGE_ORDER_DATA_FOR_COIN_SUCCESS';
export const GET_EXCHANGE_ORDER_DATA_FOR_COIN_FAILURE =
  'GET_EXCHANGE_ORDER_DATA_FOR_COIN_FAILURE';

//Get Order Book Buy Data
export const GET_ORDER_BOOK_BUY_DATA = 'GET_ORDER_BOOK_BUY_DATA';
export const GET_ORDER_BOOK_BUY_DATA_SUCCESS =
  'GET_ORDER_BOOK_BUY_DATA_SUCCESS';
export const GET_ORDER_BOOK_BUY_DATA_FAILURE =
  'GET_ORDER_BOOK_BUY_DATA_FAILURE';

//Get Order Book Sell Data
export const GET_ORDER_BOOK_SELL_DATA = 'GET_ORDER_BOOK_SELL_DATA';
export const GET_ORDER_BOOK_SELL_DATA_SUCCESS =
  'GET_ORDER_BOOK_SELL_DATA_SUCCESS';
export const GET_ORDER_BOOK_SELL_DATA_FAILURE =
  'GET_ORDER_BOOK_SELL_DATA_FAILURE';

//Get Market Trades Data
export const GET_MARKET_TRADES_DATA = 'GET_MARKET_TRADES_DATA';
export const GET_MARKET_TRADES_DATA_SUCCESS = 'GET_MARKET_TRADES_DATA_SUCCESS';
export const GET_MARKET_TRADES_DATA_FAILURE = 'GET_MARKET_TRADES_DATA_FAILURE';

//Get All coins Balance
export const GET_ALL_COINS_BALANCE = 'GET_ALL_COINS_BALANCE';
export const GET_ALL_COINS_BALANCE_SUCCESS = 'GET_ALL_COINS_BALANCE_SUCCESS';
export const GET_ALL_COINS_BALANCE_FAILURE = 'GET_ALL_COINS_BALANCE_FAILURE';

// Post Exchange All Coins Buy
export const POST_EXCHANGE_ALL_COINS_BUY = 'POST_EXCHANGE_ALL_COINS_BUY';
export const POST_EXCHANGE_ALL_COINS_BUY_SUCCESS =
  'POST_EXCHANGE_ALL_COINS_BUY_SUCCESS';
export const POST_EXCHANGE_ALL_COINS_BUY_FAILURE =
  'POST_EXCHANGE_ALL_COINS_BUY_FAILURE';

// Post Exchange All Coins Sell
export const POST_EXCHANGE_ALL_COINS_SELL = 'POST_EXCHANGE_ALL_COINS_SELL';
export const POST_EXCHANGE_ALL_COINS_SELL_SUCCESS =
  'POST_EXCHANGE_ALL_COINS_SELL_SUCCESS';
export const POST_EXCHANGE_ALL_COINS_SELL_FAILURE =
  'POST_EXCHANGE_ALL_COINS_SELL_FAILURE';

// WebSocket Connection
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_CONNECT_SUCCESS = 'WEBSOCKET_CONNECT_SUCCESS';
export const WEBSOCKET_CONNECT_FAILURE = 'WEBSOCKET_CONNECT_FAILURE';

// ExchangeOrder Websocket
export const EXCHANGE_ORDER_WEB_SOCKET = 'EXCHANGE_ORDER_WEB_SOCKET';
export const EXCHANGE_ORDER_WEB_SOCKET_SUCCESS =
  'EXCHANGE_ORDER_WEB_SOCKET_SUCCESS';
export const EXCHANGE_ORDER_WEB_SOCKET_FAILURE =
  'EXCHANGE_ORDER_WEB_SOCKET_FAILURE';
// Get Fee Details
export const GET_DEPOSITWITHDRAW_FEE = 'GET_DEPOSITWITHDRAW_FEE';
export const GET_DEPOSITWITHDRAW_FEE_SUCCESS =
  'GET_DEPOSITWITHDRAW_FEE_SUCCESS';
export const GET_DEPOSITWITHDRAW_FEE_FAILURE =
  'GET_DEPOSITWITHDRAW_FEE_FAILURE';

// Refer and Earn
export const GET_REFERRAL_DATA = 'GET_REFERRAL_DATA';
export const GET_REFERRAL_DATA_SUCCESS = 'GET_REFERRAL_DATA_SUCCESS';
export const GET_REFERRAL_DATA_FAILURE = 'GET_REFERRAL_DATA_FAILURE';

export const GET_REFERRAL_HISTORY = 'GET_REFERRAL_HISTORY';
export const GET_REFERRAL_HISTORY_SUCCESS = 'GET_REFERRAL_HISTORY_SUCCESS';
export const GET_REFERRAL_HISTORY_FAILURE = 'GET_REFERRAL_HISTORY_FAILURE';

export const GET_REWARD_HISTORY = 'GET_REWARD_HISTORY';
export const GET_REWARD_HISTORY_SUCCESS = 'GET_REWARD_HISTORY_SUCCESS';
export const GET_REWARD_HISTORY_FAILURE = 'GET_REWARD_HISTORY_FAILURE';

export const GET_MARKET_PAIR = 'GET_MARKET_PAIR';
export const GET_MARKET_PAIR_SUCCESS = 'GET_MARKET_PAIR_SUCCESS';
export const GET_MARKET_PAIR_FAILURE = 'GET_MARKET_PAIR_FAILURE';

//Profile Page
export const POST_PROFILE_IMAGE = 'POST_PROFILE_IMAGE';
export const POST_PROFILE_IMAGE_SUCCESS = 'POST_PROFILE_IMAGE_SUCCESS';
export const POST_PROFILE_IMAGE_FAILURE = 'POST_PROFILE_IMAGE_FAILURE';

export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILURE = 'GET_PROFILE_DATA_FAILURE';
// POST App PassCode
export const POST_APP_PASSCODE = 'POST_APP_PASSCODE';
export const POST_APP_PASSCODE_SUCCESS = 'POST_APP_PASSCODE_SUCCESS';
export const POST_APP_PASSCODE_FAILURE = 'POST_APP_PASSCODE_FAILURE';
// POST Notification Settings
export const POST_NOTIFICATION_SETTINGS = 'POST_NOTIFICATION_SETTINGS';
export const POST_NOTIFICATION_SETTINGS_SUCCESS =
  'POST_NOTIFICATION_SETTINGS_SUCCESS';
export const POST_NOTIFICATION_SETTINGS_FAILURE =
  'POST_NOTIFICATION_SETTINGS_FAILURE';
